version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data of Greenweeeeeeeeeez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales list
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: number of the order
          - name: pdt_id
            description: unique product id
          - name: revenue
            description: turnover's product
          - name: quantity
            description: quantity per order/product
          - name: primary_key_sales
            description: clé primaire
      - name: product
        identifier: raw_gz_product
        description: products list
        columns:
          - name: products_id
            description: unique product id
            tests:
              - unique
              - not_null
          - name: Purchase_price
            description: cost of the product
      - name: ship
        identifier: raw_gz_ship
        description: ship cost
        columns:
          - name: orders_id
            description: number of the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee of the shipping
          - name: logCost
            description: log cost
          - name: ship_cost
            description: ship cost
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords cost
      - name: bing
        identifier: raw_gz_bing
        description: bing cost
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo cost
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook cost

models:
  - name: int_campaign
    tests:
      - unique:
          column_name: "(date_date || '-' || paid_source || '-' || campaign_key)"
      - not_null:
          column_name:
            - date_date
            - paid_source
            - campaign_key
            - campaign_name
            - ads_cost
            - impression
            - click
  - name: int_campaigns_days
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date
  - name: finance_campaigns_days
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date
      

  

